// Compiles the per-unit JSON corpus into the typed modules the app imports:
//   data/words.ts  and  data/units.ts
//
//   node tools/word-gen/compile.mjs              # compile (structural validation must pass)
//   node tools/word-gen/compile.mjs --complete   # also require the full 160-unit corpus
//
// Output is deterministic (sorted by id), grouped by category/unit with comment headers.
// Strings are emitted as double-quoted TS literals (JSON.stringify) — safe for apostrophes.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadCorpus } from './lib/load.mjs';
import { validateCorpus } from './lib/schema.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');
const requireComplete = process.argv.includes('--complete');

function readArrayLiteral(file, name) {
  const src = fs.readFileSync(path.join(ROOT, file), 'utf8');
  const at = src.indexOf(name);
  const start = src.indexOf('[', at);
  const end = src.lastIndexOf(']');
  // eslint-disable-next-line no-new-func
  return new Function(`return ${src.slice(start, end + 1)}`)();
}

const s = (v) => JSON.stringify(v);              // safe TS string literal
const arr = (a) => `[${(a || []).map(s).join(', ')}]`;

function serializeWord(w) {
  const parts = [
    `id: ${w.id}`,
    `categoryId: ${w.categoryId}`,
    `unitId: ${w.unitId}`,
    `german: ${s(w.german)}`,
    `turkish: ${s(w.turkish)}`,
    `example: ${s(w.example)}`,
    `exampleTranslation: ${s(w.exampleTranslation)}`,
    `synonyms: ${arr(w.synonyms)}`,
    `level: ${s(w.level)}`,
  ];
  if (w.audioUrl) parts.push(`audioUrl: ${s(w.audioUrl)}`);
  return `  { ${parts.join(', ')} },`;
}

function main() {
  const { words, units } = loadCorpus();
  const errors = validateCorpus(words, units, { requireComplete });
  if (errors.length) {
    console.error(`❌ Refusing to compile — ${errors.length} validation error(s):`);
    for (const e of errors.slice(0, 60)) console.error('  - ' + e);
    if (errors.length > 60) console.error(`  ... and ${errors.length - 60} more`);
    process.exit(1);
  }

  const categories = readArrayLiteral('data/categories.ts', 'CATEGORIES');
  const catName = new Map(categories.map((c) => [c.id, c.name]));

  // ---- data/words.ts ----
  const wHeader =
`export type Word = {
  id: number;
  categoryId: number;
  unitId: number;
  german: string;
  turkish: string;
  example: string;
  exampleTranslation: string;
  synonyms?: string[];
  level: 'A1' | 'A2' | 'B1' | 'B2' | 'C1';
  audioUrl?: string;
};

// AUTO-GENERATED by tools/word-gen/compile.mjs — do not edit by hand.
// Source of truth: tools/word-gen/units/*.json  (edit there, then re-run compile).
export const WORDS: Word[] = [`;

  const wLines = [wHeader];
  const unitById = new Map(units.map((u) => [u.id, u]));
  const wordsByUnit = new Map();
  for (const w of words) {
    if (!wordsByUnit.has(w.unitId)) wordsByUnit.set(w.unitId, []);
    wordsByUnit.get(w.unitId).push(w);
  }
  // Emit grouped by category, then unit number.
  for (const u of units) {
    const uw = (wordsByUnit.get(u.id) || []).sort((a, b) => a.id - b.id);
    wLines.push(`  // ─── Kategori ${u.categoryId} (${catName.get(u.categoryId) || ''}), Ünite ${u.number} — ${u.title} ───`);
    for (const w of uw) wLines.push(serializeWord(w));
  }
  wLines.push('];', '');
  fs.writeFileSync(path.join(ROOT, 'data/words.ts'), wLines.join('\n'));

  // ---- data/units.ts ----
  const uHeader =
`export type Unit = {
  id: number;
  categoryId: number;
  number: number;
  title: string;
  wordCount: number;
};

// AUTO-GENERATED by tools/word-gen/compile.mjs — do not edit by hand.
export const UNITS: Unit[] = [`;

  const uLines = [uHeader];
  let lastCat = null;
  for (const u of units) {
    if (u.categoryId !== lastCat) {
      uLines.push(`  // Kategori ${u.categoryId} — ${catName.get(u.categoryId) || ''}`);
      lastCat = u.categoryId;
    }
    uLines.push(`  { id: ${u.id}, categoryId: ${u.categoryId}, number: ${u.number}, title: ${s(u.title)}, wordCount: ${u.wordCount} },`);
  }
  uLines.push('];', '');
  fs.writeFileSync(path.join(ROOT, 'data/units.ts'), uLines.join('\n'));

  console.log(`✅ Compiled ${words.length} words / ${units.length} units → data/words.ts, data/units.ts`);
}

main();
