// Data-integrity tests for the compiled vocabulary corpus.
// The source of truth is tools/word-gen/units/*.json; data/words.ts + data/units.ts are
// generated by tools/word-gen/compile.mjs. These tests guard the app-facing invariants.

import { WORDS } from '@/data/words';
import { UNITS } from '@/data/units';
import { CATEGORIES } from '@/data/categories';

const LEVELS = ['A1', 'A2', 'B1', 'B2', 'C1'];
const ARTICLES = ['der', 'die', 'das'];
const WORDS_PER_UNIT = 15;
const UNITS_PER_CATEGORY = 20;

describe('vocabulary corpus', () => {
  test('has the full curriculum: 2400 words, 160 units, 8 categories', () => {
    expect(WORDS.length).toBe(2400);
    expect(UNITS.length).toBe(160);
    expect(CATEGORIES.length).toBe(8);
  });

  test('every word id is a unique positive integer', () => {
    const ids = new Set<number>();
    for (const w of WORDS) {
      expect(Number.isInteger(w.id)).toBe(true);
      expect(w.id).toBeGreaterThan(0);
      expect(ids.has(w.id)).toBe(false);
      ids.add(w.id);
    }
  });

  test('every German headword is globally unique', () => {
    const seen = new Map<string, number>();
    const dups: string[] = [];
    for (const w of WORDS) {
      const key = w.german.trim().toLowerCase().replace(/\s+/g, ' ');
      if (seen.has(key)) dups.push(`${w.german} (ids ${seen.get(key)}, ${w.id})`);
      else seen.set(key, w.id);
    }
    expect(dups).toEqual([]);
  });

  test('every word has non-empty required fields and a valid level', () => {
    for (const w of WORDS) {
      expect(w.german.trim().length).toBeGreaterThan(0);
      expect(w.turkish.trim().length).toBeGreaterThan(0);
      expect(w.example.trim().length).toBeGreaterThan(0);
      expect(w.exampleTranslation.trim().length).toBeGreaterThan(0);
      expect(LEVELS).toContain(w.level);
    }
  });

  test('noun headwords (der/die/das X) capitalize the noun', () => {
    const bad: string[] = [];
    for (const w of WORDS) {
      const tokens = w.german.trim().split(/\s+/);
      if (tokens.length === 2 && ARTICLES.includes(tokens[0].toLowerCase())) {
        if (tokens[1][0] !== tokens[1][0].toUpperCase()) bad.push(w.german);
      }
    }
    expect(bad).toEqual([]);
  });

  test('no synonym equals its own headword', () => {
    const bad: string[] = [];
    for (const w of WORDS) {
      const hk = w.german.trim().toLowerCase();
      for (const s of w.synonyms ?? []) {
        if (s.trim().toLowerCase() === hk) bad.push(`${w.german} (id ${w.id})`);
      }
    }
    expect(bad).toEqual([]);
  });

  test('each unit has exactly 15 words, all matching the unit category', () => {
    const byUnit = new Map<number, number>();
    const unitCat = new Map(UNITS.map((u) => [u.id, u.categoryId]));
    for (const w of WORDS) {
      byUnit.set(w.unitId, (byUnit.get(w.unitId) ?? 0) + 1);
      expect(unitCat.get(w.unitId)).toBe(w.categoryId);
    }
    for (const u of UNITS) {
      expect(byUnit.get(u.id)).toBe(WORDS_PER_UNIT);
      expect(u.wordCount).toBe(WORDS_PER_UNIT);
    }
  });

  test('each category has exactly 20 units, numbered 1..20', () => {
    for (const c of CATEGORIES) {
      const us = UNITS.filter((u) => u.categoryId === c.id).map((u) => u.number).sort((a, b) => a - b);
      expect(us.length).toBe(UNITS_PER_CATEGORY);
      expect(us).toEqual(Array.from({ length: UNITS_PER_CATEGORY }, (_, i) => i + 1));
    }
  });

  test('every word references a real unit', () => {
    const unitIds = new Set(UNITS.map((u) => u.id));
    for (const w of WORDS) expect(unitIds.has(w.unitId)).toBe(true);
  });
});
